from enum import Enum


class ErrorCode(str, Enum):
    COMMON_INTERNAL_SERVER_ERROR = "COMMON_INTERNAL_SERVER_ERROR"
    COMMON_VALIDATION_ERROR = "COMMON_VALIDATION_ERROR"

    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_USER_NOT_ACTIVE = "AUTH_USER_NOT_ACTIVE"
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
    AUTH_UNAUTHENTICATED = "AUTH_UNAUTHENTICATED"
    AUTH_REFRESH_TOKEN_REUSED = "AUTH_REFRESH_TOKEN_REUSED"
