// This file will be auto-generated by `supabase gen types typescript`
// after the initial migration is applied.
// For now, export an empty placeholder type.
export type Database = Record<string, never>;
