# -*- coding: utf-8 -*-
"""detect-musical-key

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuZbJfWWQgHmL83d558jxkkkxm5aK0cj
"""

!pip install essentia yt-dlp --quiet



import subprocess, glob, os
import numpy as np
import essentia.standard as es

def detect_keys_from_youtube(url, win_sec=15, hop_sec=5,
                             switch_penalty=6.0, prior_weight=2.0):
    # ---- 다운로드 ----
    for f in glob.glob("audio.*"):
        os.remove(f)
    r = subprocess.run([
        "yt-dlp", "-x", "--audio-format", "wav", "--audio-quality", "0",
        "-o", "audio.%(ext)s", url
    ], capture_output=True, text=True)
    if r.returncode != 0:
        print("다운로드 실패:\n", r.stderr[-500:]); return

    path = glob.glob("audio.*")[0]
    audio = es.MonoLoader(filename=path)()
    sr = 44100
    win, hop = int(sr*win_sec), int(sr*hop_sec)

    # ---- 1) 구간별 키 추출 ----
    raw = []
    for start in range(0, max(1, len(audio)-win+1), hop):
        seg = audio[start:start+win].copy()
        k, s, st = es.KeyExtractor()(seg)
        raw.append((start/sr, f"{k} {s}", st))

    # ---- 2) 비터비 평활화 + 전역 사전확률 ----
    states = sorted({k for _, k, _ in raw})
    S = len(states); idx = {k: i for i, k in enumerate(states)}

    support = np.zeros(S)
    for _, k, st in raw: support[idx[k]] += st
    prior = np.log(support/support.sum() + 1e-6) * prior_weight

    def emit(rep, st):
        p = np.full(S, (1.0-st)/(S-1)); p[idx[rep]] = st
        return np.log(p + 1e-9) + prior

    T = len(raw)
    dp = np.full((T, S), -1e18); bp = np.zeros((T, S), dtype=int)
    dp[0] = emit(raw[0][1], raw[0][2])
    for t in range(1, T):
        e = emit(raw[t][1], raw[t][2])
        for s in range(S):
            tr = dp[t-1] - switch_penalty; tr[s] = dp[t-1][s]
            b = int(np.argmax(tr)); dp[t][s] = tr[b] + e[s]; bp[t][s] = b
    path = [int(np.argmax(dp[-1]))]
    for t in range(T-1, 0, -1): path.append(bp[t][path[-1]])
    smooth = [states[i] for i in path[::-1]]

    # ---- 3) 구간 압축 ----
    segs = []
    for t, (sec, _, _) in enumerate(raw):
        if not segs or segs[-1][1] != smooth[t]:
            segs.append((sec, smooth[t]))

    # ---- 출력 ----
    print("=" * 40)
    for sec, k in segs:
        print(f"  {sec:6.1f}s 부터 : {k}")
    changes = segs[1:]
    print("=" * 40)
    if changes:
        print(f"키 변화 {len(changes)}회:")
        for sec, k in changes:
            print(f"  - {sec:.0f}초 부근 → {k}")
    else:
        print(f"단일 키 곡: {segs[0][1]}")
    print("=" * 40)
    return segs, raw

!pip install librosa yt-dlp --quiet

import subprocess, glob, os
import numpy as np
import librosa

PITCH = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B']
MAJOR = np.array([6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88])
MINOR = np.array([6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17])

def detect_key_librosa(y, sr):
    """Essentia KeyExtractor 대체: 크로마(chroma) + Krumhansl 상관 매칭"""
    chroma = librosa.feature.chroma_cqt(y=y, sr=sr).mean(axis=1)
    if chroma.sum() > 0:
        chroma = chroma / chroma.sum()
    best_k, best_s, best_c = "C", "major", -2.0
    for i in range(12):
        for prof, name in [(MAJOR,'major'), (MINOR,'minor')]:
            c = np.corrcoef(chroma, np.roll(prof, i))[0,1]
            if c > best_c:
                best_c, best_k, best_s = c, PITCH[i], name
    strength = max(0.0, min(1.0, best_c))   # 신뢰도 0~1 클램프
    return best_k, best_s, strength


def detect_keys_from_youtube(url, win_sec=15, hop_sec=5,
                             switch_penalty=6.0, prior_weight=2.0):
    # ---- 다운로드 ----
    for f in glob.glob("audio.*"):
        os.remove(f)
    r = subprocess.run([
        "yt-dlp", "-x", "--audio-format", "wav", "--audio-quality", "0",
        "-o", "audio.%(ext)s", url
    ], capture_output=True, text=True)
    if r.returncode != 0:
        print("다운로드 실패:\n", r.stderr[-500:]); return

    path = glob.glob("audio.*")[0]
    # ---- MonoLoader 대체 ----
    audio, sr = librosa.load(path, sr=44100, mono=True)
    win, hop = int(sr*win_sec), int(sr*hop_sec)

    # ---- 1) 구간별 키 추출 ----
    raw = []
    for start in range(0, max(1, len(audio)-win+1), hop):
        seg = audio[start:start+win].copy()
        k, s, st = detect_key_librosa(seg, sr)
        raw.append((start/sr, f"{k} {s}", st))

    # ---- 2) 비터비 평활화 + 전역 사전확률 (원본과 동일) ----
    states = sorted({k for _, k, _ in raw})
    S = len(states); idx = {k: i for i, k in enumerate(states)}

    support = np.zeros(S)
    for _, k, st in raw: support[idx[k]] += st
    prior = np.log(support/support.sum() + 1e-6) * prior_weight

    def emit(rep, st):
        p = np.full(S, (1.0-st)/(S-1)); p[idx[rep]] = st
        return np.log(p + 1e-9) + prior

    T = len(raw)
    dp = np.full((T, S), -1e18); bp = np.zeros((T, S), dtype=int)
    dp[0] = emit(raw[0][1], raw[0][2])
    for t in range(1, T):
        e = emit(raw[t][1], raw[t][2])
        for s in range(S):
            tr = dp[t-1] - switch_penalty; tr[s] = dp[t-1][s]
            b = int(np.argmax(tr)); dp[t][s] = tr[b] + e[s]; bp[t][s] = b
    path = [int(np.argmax(dp[-1]))]
    for t in range(T-1, 0, -1): path.append(bp[t][path[-1]])
    smooth = [states[i] for i in path[::-1]]

    # ---- 3) 구간 압축 ----
    segs = []
    for t, (sec, _, _) in enumerate(raw):
        if not segs or segs[-1][1] != smooth[t]:
            segs.append((sec, smooth[t]))

    # ---- 출력 ----
    print("=" * 40)
    for sec, k in segs:
        print(f"  {sec:6.1f}s 부터 : {k}")
    changes = segs[1:]
    print("=" * 40)
    if changes:
        print(f"키 변화 {len(changes)}회:")
        for sec, k in changes:
            print(f"  - {sec:.0f}초 부근 → {k}")
    else:
        print(f"단일 키 곡: {segs[0][1]}")
    print("=" * 40)
    return segs, raw

import subprocess, glob, os, time
import numpy as np
import pandas as pd
import essentia.standard as es
import librosa

PITCH = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B']
MAJOR = np.array([6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88])
MINOR = np.array([6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17])

# ---- 방식 A: Essentia KeyExtractor ----
def key_essentia(seg, sr):
    k, s, st = es.KeyExtractor()(seg.astype(np.float32))
    return k, s, st

# ---- 방식 B: librosa + Krumhansl ----
def key_librosa(seg, sr):
    chroma = librosa.feature.chroma_cqt(y=seg, sr=sr).mean(axis=1)
    if chroma.sum() > 0: chroma /= chroma.sum()
    bk, bs, bc = "C", "major", -2.0
    for i in range(12):
        for prof, name in [(MAJOR,'major'), (MINOR,'minor')]:
            c = np.corrcoef(chroma, np.roll(prof, i))[0,1]
            if c > bc: bc, bk, bs = c, PITCH[i], name
    return bk, bs, max(0.0, min(1.0, bc))

# ---- 공통: 구간별 분석 + 비터비 (key_fn만 교체) ----
def analyze(audio, sr, key_fn, win_sec=15, hop_sec=5,
            switch_penalty=6.0, prior_weight=2.0):
    win, hop = int(sr*win_sec), int(sr*hop_sec)
    raw = []
    for start in range(0, max(1, len(audio)-win+1), hop):
        k, s, st = key_fn(audio[start:start+win].copy(), sr)
        raw.append((start/sr, f"{k} {s}", st))

    states = sorted({k for _, k, _ in raw}); S = len(states)
    idx = {k: i for i, k in enumerate(states)}
    support = np.zeros(S)
    for _, k, st in raw: support[idx[k]] += st
    prior = np.log(support/support.sum() + 1e-6) * prior_weight

    def emit(rep, st):
        p = np.full(S, (1.0-st)/(S-1)); p[idx[rep]] = st
        return np.log(p + 1e-9) + prior

    T = len(raw); dp = np.full((T,S), -1e18); bp = np.zeros((T,S), dtype=int)
    dp[0] = emit(raw[0][1], raw[0][2])
    for t in range(1, T):
        e = emit(raw[t][1], raw[t][2])
        for s in range(S):
            tr = dp[t-1] - switch_penalty; tr[s] = dp[t-1][s]
            b = int(np.argmax(tr)); dp[t][s] = tr[b] + e[s]; bp[t][s] = b
    path = [int(np.argmax(dp[-1]))]
    for t in range(T-1, 0, -1): path.append(bp[t][path[-1]])
    smooth = [states[i] for i in path[::-1]]

    segs = []
    for t, (sec, _, _) in enumerate(raw):
        if not segs or segs[-1][1] != smooth[t]:
            segs.append((sec, smooth[t]))
    return segs

def chain(segs): return " → ".join(k.split()[0] for _, k in segs)

# ---- 두 방식 비교 (다운로드 1회 → 둘 다 분석) ----
def compare_methods(urls, **kw):
    rows = []
    for i, url in enumerate(urls, 1):
        print(f"\n{'='*55}\n[{i}/{len(urls)}] {url}\n{'='*55}")
        for f in glob.glob("audio.*"): os.remove(f)
        r = subprocess.run(
            ["yt-dlp","-x","--audio-format","wav","--audio-quality","0",
             "-o","audio.%(ext)s", url], capture_output=True, text=True)
        if r.returncode != 0:
            print("  다운로드 실패");
            rows.append({"링크":url[-15:],"Essentia":"실패","Ess(s)":"-",
                         "librosa":"실패","lib(s)":"-","일치":"-"}); continue

        path = glob.glob("audio.*")[0]
        audio, sr = librosa.load(path, sr=44100, mono=True)

        # 방식 A
        t0=time.perf_counter(); e_seg=analyze(audio,sr,key_essentia,**kw); e_t=time.perf_counter()-t0
        # 방식 B
        t0=time.perf_counter(); l_seg=analyze(audio,sr,key_librosa,**kw); l_t=time.perf_counter()-t0

        ec, lc = chain(e_seg), chain(l_seg)
        print(f"  Essentia: {ec}  ({e_t:.1f}s)")
        print(f"  librosa : {lc}  ({l_t:.1f}s)")
        rows.append({"링크":url[-15:], "Essentia":ec, "Ess(s)":round(e_t,1),
                     "librosa":lc, "lib(s)":round(l_t,1),
                     "일치":"O" if ec==lc else "X"})

    df = pd.DataFrame(rows)
    print(f"\n{'='*55}\n방식 비교 결과 (Essentia vs librosa)\n{'='*55}")
    print(df.to_string(index=False))

    valid = [r for r in rows if r["일치"] in ("O","X")]
    if valid:
        agree = sum(1 for r in valid if r["일치"]=="O")
        es_avg = np.mean([r["Ess(s)"] for r in valid])
        lb_avg = np.mean([r["lib(s)"] for r in valid])
        print(f"\n결과 일치: {agree}/{len(valid)}곡")
        print(f"평균 분석속도 — Essentia {es_avg:.1f}s / librosa {lb_avg:.1f}s")
    return df

# ===== 여기에 비교할 링크들을 넣으세요 =====
urls = [
    "https://www.youtube.com/watch?v=s9gOnp_tWSw",
    "https://www.youtube.com/watch?v=2BGqpzWQC7A",
    "https://www.youtube.com/watch?v=rR5wyv1olsQ",
    "https://www.youtube.com/watch?v=6dN76tev5jo",
    "https://www.youtube.com/watch?v=rR5wyv1olsQ",
    "https://www.youtube.com/watch?v=jc1Qx7rijBU"
]

result_df = compare_methods(urls)