from enum import Enum


class ErrorCode(str, Enum):
    COMMON_INTERNAL_SERVER_ERROR = "COMMON_INTERNAL_SERVER_ERROR"
    COMMON_VALIDATION_ERROR = "COMMON_VALIDATION_ERROR"

    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_USER_NOT_ACTIVE = "AUTH_USER_NOT_ACTIVE"
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
    AUTH_UNAUTHENTICATED = "AUTH_UNAUTHENTICATED"
    AUTH_CSRF_TOKEN_INVALID = "AUTH_CSRF_TOKEN_INVALID"
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID"
    AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_TOKEN_EXPIRED"
    AUTH_REFRESH_TOKEN_REUSED = "AUTH_REFRESH_TOKEN_REUSED"

    WORKSPACE_OWNER_TRANSFER_REQUIRED = "WORKSPACE_OWNER_TRANSFER_REQUIRED"
    WORKSPACE_INVITE_INVALID = "WORKSPACE_INVITE_INVALID"
    WORKSPACE_FORBIDDEN = "WORKSPACE_FORBIDDEN"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"

    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_FORBIDDEN = "PROJECT_FORBIDDEN"
